AWSTemplateFormatVersion: '2010-09-09'
Description: 'connections LC for ASG'
Parameters:
  HealthCheckPath:
    Type: String
    Description: "Specify the Health Check Path for target Group"
    Default: "/"
  ALBTargetGroupPort:
    Description: Enter the Port for ALB Target Group
    Type: String
    Default: 80    
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: "Choose the VPC where the Target group should be created"
    Default: vpc-3b83675d
  ALBTargetGroupName:
    Type: String
    Description: "Enter the name of the Target Group"
    Default: "smartworks-alb-tg"
  ImageId:
    Description: "Image Id for EC2"
    Type: String
    Default: ami-0d4761e6d579846f9
  SecurityGroupID:
    Description: "SGID"
    Type: AWS::EC2::SecurityGroup::Id   
    Default: sg-0908f87618a8b122f
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Default: t3.micro
  myPublicSubnet1:
    Description: "subnet"
    Type: String   
    Default: subnet-9629e0f0
Resources:
  smartworksALBTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      Port: !Ref ALBTargetGroupPort
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      TargetType: "instance"
      Matcher: 
        HttpCode: "200"
      HealthyThresholdCount: 5
      VpcId: !Ref VPC
      Name: !Ref ALBTargetGroupName
      HealthCheckEnabled: true
