AWSTemplateFormatVersion: '2010-09-09'
Description: 'connections LC for ASG'
Parameters:
  ImageId:
    Description: "Image Id for EC2"
    Type: String
    Default: ami-0d4761e6d579846f9
  SecurityGroupID:
    Description: "SGID"
    Type: AWS::EC2::SecurityGroup::Id   
    Default: sg-0908f87618a8b122f
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Default: t3.micro
  myPublicSubnet1:
    Description: "subnet"
    Type: String   
    Default: subnet-9629e0f0
  myLaunchTemplateVersionNumber:
    Type: String  
Resources:
  myServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - !Ref myPublicSubnet1
      LaunchTemplate:   
        LaunchTemplateId: lt-0857ccb73da20a2cb
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 300
      MaxInstanceLifetime: 2592000
