Resources:
  smartworksALBTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      Port: !Ref ALBTargetGroupPort
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      TargetType: "instance"
      Matcher: 
        HttpCode: "200"
      HealthyThresholdCount: 5
      VpcId: !Ref VPC
      Name: !Ref ALBTargetGroupName
      HealthCheckEnabled: true
  mySimpleConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
          Fn::Sub: "${ImageId}" 
      SecurityGroups:  
      - !Ref SecurityGroupID
      InstanceType:  
          Ref: "InstanceType"
  myServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - !Ref myPublicSubnet1
      LaunchConfigurationName: !Ref mySimpleConfig
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '2'
      HealthCheckGracePeriod: 300
      MaxInstanceLifetime: 2592000
      TargetGroupARNs:
      - !Ref smartworksALBTargetGroup     
    DependsOn:
      - smartworksALBTargetGroup
